---
roles:
  base:
    provisioners:
      - type: hosts
        name: 'base networking'
        preserve_order: true
        sync_hosts: true
        add_localhost_hostnames: false
        hosts:
          - ['@vagrant_ssh', ['@vagrant_hostnames']]
        imports: ['global']
        exports:
          global:
            - ['@vagrant_ssh', ['@vagrant_hostnames']]

  pe-puppet-master:
    private_networks:
      - {auto_network: true}
    providers:
      - type: vmware_fusion
        vmx: { memsize: 4096, numvcpus: 4}
    provisioners:
      - type: pe_bootstrap
        role: !ruby/sym master
        answer_extras:
          - '"puppet_enterprise::profile::master::code_manager_auto_configure": true'
          - '"puppet_enterprise::profile::master::r10k_remote": "https://github.com/trlinkin/ci_control.git"'
      - type: shell
        path: 'data/pe_post_provision.sh'

  pe-puppet-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: 'curl -k https://master.puppet.vm:8140/packages/current/install.bash | sudo bash'}

  stop-firewall:
    provisioner:
      - {type: shell, inline: 'puppet resource service firewalld ensure=stopped' }

  run_puppet_agent:
    provisioner:
      - {type: shell, inline: '/usr/local/bin/puppet agent -t' }
